// Registro de entidades. Cada entrada describe una tabla migrada desde el
// diccionario Clarion para que el CRUD genérico sepa cómo operar sobre ella.
//
//   table     -> nombre de la tabla en PostgreSQL
//   pk        -> columna(s) que forman la clave primaria
//   columns   -> columnas que se aceptan al crear/actualizar
//   search    -> columnas usadas por el filtro de texto (?q=)
//   orderBy   -> orden por defecto del listado
//   label     -> nombre legible (Browse de Clarion del que proviene)

export const entities = {
  usuarios: {
    table: 'ususu',
    pk: ['usuario'],
    columns: ['usuario', 'nombre', 'principal'],
    search: ['usuario', 'nombre'],
    orderBy: 'usuario',
    label: 'Usuarios del Sistema',
  },
  clientes: {
    table: 'clie',
    pk: ['codigo'],
    columns: ['codigo', 'nombrecliente', 'contrato', 'ciudad', 'prefijo', 'rutaexport', 'email', 'liderproyecto', 'noticliente'],
    search: ['codigo', 'nombrecliente', 'ciudad', 'email'],
    orderBy: 'codigo',
    label: 'Clientes',
    autoConsecutivo: {
      field: 'codigo',
      acnsPrefijo: 'CLIE',
      pad: 3,
    },
  },
  funcionarios: {
    table: 'clief',
    pk: ['codigo', 'documento'],
    columns: ['codigo', 'documento', 'nombre', 'cargo', 'estado', 'email', 'tratamiento'],
    search: ['documento', 'nombre', 'cargo', 'email'],
    orderBy: 'nombre',
    label: 'Funcionarios del Cliente',
    editablePk: ['documento'],
    filterColumns: ['codigo', 'estado'],
    filterColumnsCaseInsensitive: ['estado'],
    excludeCapacitaParam: 'excludeCnscapacita',
  },
  soportes: {
    table: 'soport',
    pk: ['codigo'],
    columns: ['codigo', 'nombre', 'documento', 'estado', 'usuario', 'clave', 'email', 'firma', 'firma_fecha'],
    listSelect: 'codigo, nombre, documento, estado, usuario, email, firma_fecha',
    responseOmit: ['clave'],
    search: ['codigo', 'nombre', 'documento', 'usuario'],
    orderBy: 'codigo',
    label: 'Soportes Técnicos',
    excludeCapacitaParam: 'excludeCnscapacita',
    excludeCapacitaSoport: true,
    filterColumns: ['estado'],
    filterColumnsCaseInsensitive: ['estado'],
    autoConsecutivo: {
      field: 'codigo',
      acnsPrefijo: 'SOP',
      pad: 4,
    },
  },
  areas_soporte: {
    table: 'soparea',
    pk: ['codigo'],
    columns: ['codigo', 'nombre', 'estado'],
    search: ['codigo', 'nombre'],
    orderBy: 'nombre',
    label: 'Áreas de Soporte',
    filterColumns: ['estado'],
    filterColumnsCaseInsensitive: ['estado'],
  },
  agenda_contactos: {
    table: 'agcon',
    pk: ['codigo'],
    columns: [
      'codigo',
      'nombre',
      'cargo',
      'email',
      'empresa',
      'telefono',
      'categoria',
      'cliente',
      'estado',
      'notas',
    ],
    listSelect:
      'codigo, nombre, cargo, email, empresa, telefono, categoria, cliente, estado',
    search: ['codigo', 'nombre', 'cargo', 'email', 'empresa'],
    orderBy: 'nombre',
    label: 'Agenda de Contactos',
    filterColumns: ['estado', 'categoria'],
    filterColumnsCaseInsensitive: ['estado', 'categoria'],
    autoConsecutivo: {
      field: 'codigo',
      acnsPrefijo: 'AGC',
      pad: 4,
    },
  },
  companias: {
    table: 'login',
    pk: ['compania'],
    columns: ['compania', 'razonsocial', 'servidor', 'bdatos', 'logo', 'nit', 'codigohab', 'direccion', 'telefono'],
    search: ['compania', 'razonsocial', 'nit'],
    orderBy: 'razonsocial',
    label: 'Compañías',
  },
  tablagenerica: {
    table: 'tgen',
    pk: ['tabla', 'campo', 'codigo'],
    columns: ['tabla', 'campo', 'codigo', 'descripcion', 'valor1', 'dato1'],
    search: ['tabla', 'campo', 'codigo', 'descripcion'],
    orderBy: 'tabla, campo, codigo',
    label: 'Tabla Genérica',
  },
  agenda: {
    table: 'agen',
    pk: ['cnsevento'],
    columns: ['cnsevento', 'descripcion', 'usuario', 'idevento', 'codigo', 'fecha', 'f_limite', 'estado'],
    search: ['cnsevento', 'descripcion', 'usuario'],
    orderBy: 'fecha DESC',
    label: 'Mi Agenda',
  },
  semanas: {
    table: 'tsema',
    pk: ['idsemana'],
    columns: ['idsemana', 'fechaini', 'fechafin', 'observacion'],
    search: ['idsemana', 'observacion'],
    orderBy: 'fechaini DESC',
    label: 'Semanas',
    listDateFilters: {
      fechaini: { column: 'fechafin', op: 'column_gte' },
      fechafin: { column: 'fechaini', op: 'column_lte' },
    },
  },
  bitacora_encabezados: {
    table: 'bite',
    pk: ['cnsbite'],
    columns: ['cnsbite', 'idsemana', 'soporte'],
    search: ['cnsbite', 'idsemana', 'soporte'],
    orderBy: 'cnsbite DESC',
    label: 'Encabezado Bitácora',
    autoConsecutivo: {
      field: 'cnsbite',
      acnsPrefijo: 'BITE',
      pad: 8,
    },
    listFrom: 'bite b INNER JOIN tsema t ON t.idsemana = b.idsemana',
    listSelect:
      'b.cnsbite, b.idsemana, b.soporte, t.observacion, t.fechaini, t.fechafin',
    listSearch: ['b.cnsbite', 'b.idsemana', 'b.soporte', 't.observacion'],
    listDateFilters: {
      fechaini: { column: 't.fechafin', op: 'column_gte' },
      fechafin: { column: 't.fechaini', op: 'column_lte' },
      ano: { column: 'b.idsemana', op: 'like_suffix' },
    },
  },
  bitacora: {
    table: 'bita',
    pk: ['cnssoporte'],
    columns: ['cnssoporte', 'fecha', 'cliente', 'soporte', 'funcionario', 'clase', 'solicitud', 'respuesta', 'estado', 'fechar', 'observaciones', 'medio', 'cnsbite', 'firma', 'firma_fecha', 'imagenes_soporte'],
    search: ['cnssoporte', 'cliente', 'funcionario', 'solicitud'],
    orderBy: 'fecha DESC',
    label: 'Bitácora de Soporte',
    autoConsecutivo: {
      field: 'cnssoporte',
      acnsPrefijo: 'BITA',
      pad: 8,
    },
    filterColumns: ['cnsbite', 'cliente', 'estado'],
    listFrom: 'bita b LEFT JOIN clie c ON c.codigo = b.cliente',
    listSelect:
      'b.cnssoporte, b.fecha, b.cliente, b.soporte, b.funcionario, b.clase, b.solicitud, b.respuesta, b.estado, b.fechar, b.observaciones, b.medio, b.cnsbite, b.firma_fecha, c.nombrecliente, '
      + '(CASE WHEN COALESCE(TRIM(b.imagenes_soporte), \'\') NOT IN (\'\', \'[]\') '
      + 'THEN jsonb_array_length(b.imagenes_soporte::jsonb) ELSE 0 END) AS imagenes_count',
    listSearch: ['b.cnssoporte', 'b.cliente', 'b.funcionario', 'b.solicitud', 'c.nombrecliente'],
    tableAlias: 'b',
  },
  informes: {
    table: 'infor',
    pk: ['consecutivo'],
    columns: ['consecutivo', 'fecha', 'cliente', 'informe', 'pendientes', 'ciudad'],
    search: ['consecutivo', 'cliente', 'informe'],
    orderBy: 'fecha DESC',
    label: 'Informes Diarios',
  },
  requerimientos: {
    table: 'desa',
    pk: ['consecutivo'],
    columns: ['consecutivo', 'cliente', 'fecha', 'requerimiento', 'desarrollo', 'modulo', 'estado', 'cnsixver', 'para', 'f_entrega', 'usuario'],
    search: ['consecutivo', 'cliente', 'requerimiento', 'modulo'],
    orderBy: 'fecha DESC',
    label: 'Requerimientos de Desarrollo',
  },
  solicitudes: {
    table: 'sreq',
    pk: ['cnssolicitud'],
    columns: ['cnssolicitud', 'usuario', 'requerimiento', 'observaciones', 'estado', 'respuesta', 'solicita', 'autoriza', 'fecha', 'f_cierre', 'modulo', 'devuelto', 'razondevol', 'idapp', 'procedimiento', 'ruta', 'usuarioasig', 'planteamiento', 'asignado'],
    search: ['cnssolicitud', 'usuario', 'requerimiento', 'solicita'],
    orderBy: 'fecha DESC',
    label: 'Solicitudes de Requerimientos',
  },
  licencias: {
    table: 'licen',
    pk: ['consecutivo'],
    columns: ['consecutivo', 'fecha', 'cliente', 'usuario', 'f_corte', 'observaciones'],
    search: ['consecutivo', 'cliente', 'usuario'],
    orderBy: 'fecha DESC',
    label: 'Licencias',
  },
  ixver: {
    table: 'ixver',
    pk: ['idreq'],
    columns: ['idreq', 'fecha', 'usuario', 'idmodulo', 'requerimiento', 'estado', 'proyecto', 'idapp', 'idproc'],
    search: ['idreq', 'usuario', 'requerimiento', 'proyecto'],
    orderBy: 'fecha DESC',
    label: 'Ixver (Requerimientos Web)',
  },
  codigospruebas: {
    table: 'codip',
    pk: ['codigo'],
    columns: ['codigo', 'descripcion', 'clase'],
    search: ['codigo', 'descripcion', 'clase'],
    orderBy: 'codigo',
    label: 'Códigos de Prueba',
  },
  asignaciones: {
    table: 'asigp',
    pk: ['consecutivo'],
    columns: ['consecutivo', 'semana', 'fecha'],
    search: ['consecutivo', 'semana'],
    orderBy: 'fecha DESC',
    label: 'Asignación de Proyectos',
  },
  entregas: {
    table: 'ent',
    pk: ['cnsentrega'],
    columns: ['cnsentrega', 'fecha', 'usuario', 'clase', 'estado', 'usuariorec', 'fecharec'],
    search: ['cnsentrega', 'usuario'],
    orderBy: 'fecha DESC',
    label: 'Entregas a Desarrollo',
  },
  variables: {
    table: 'usvgs',
    pk: ['idvariable'],
    columns: ['idvariable', 'descripcion', 'tp_variable', 'dato', 'indvigencia', 'observacion', 'tabla', 'campo_codigo'],
    search: ['idvariable', 'descripcion'],
    orderBy: 'idvariable',
    label: 'Variables del Sistema',
  },
  capacitaciones: {
    table: 'rasist',
    pk: ['cnscapacita'],
    columns: ['cnscapacita', 'fecha', 'capacitador', 'tema', 'tema1', 'tema2', 'tema3', 'duracion', 'cliente', 'compromiso', 'compromiso1', 'compromiso2', 'estado', 'cnscrono', 'tema_codigo'],
    search: ['cnscapacita', 'capacitador', 'tema', 'cliente'],
    orderBy: 'fecha DESC',
    label: 'Control de Capacitaciones',
    autoConsecutivo: {
      field: 'cnscapacita',
      acnsPrefijo: 'RASIST',
      leadingPrefix: '01',
      pad: 8,
    },
  },
  asistentes: {
    table: 'rasistd',
    pk: ['cnscapacita', 'item'],
    columns: ['cnscapacita', 'item', 'documento', 'nombres', 'cargo', 'firma', 'firma_fecha'],
    search: ['documento', 'nombres', 'cargo'],
    orderBy: 'item',
    label: 'Asistentes a Capacitaciones',
    filterColumns: ['cnscapacita'],
  },
  temas_capacitacion: {
    table: 'captema',
    tableAlias: 'c',
    pk: ['codigo'],
    columns: ['codigo', 'nombre', 'estado', 'observacion', 'dirigidoa', 'qrys_grupo', 'cnplan', 'modulo_codigo', 'modulo_nombre', 'modulo_orden'],
    search: ['codigo', 'nombre'],
    listSearch: ['c.codigo', 'c.nombre', 'g.nombre', 'c.qrys_grupo', 'c.modulo_nombre', 'c.cnplan'],
    orderBy: 'c.codigo',
    listFrom: `captema c
      LEFT JOIN qrysgrupo g ON g.codigo = c.qrys_grupo
      LEFT JOIN LATERAL (
        SELECT p.modulo, m.nombre AS modulo_nombre, m.orden AS modulo_orden
        FROM qrysgrupod gd
        JOIN qrysproc p ON p.codigo = gd.proceso
        LEFT JOIN qrysmod m ON m.codigo = p.modulo
        WHERE gd.grupo = c.qrys_grupo AND c.modulo_codigo IS NULL
        ORDER BY m.orden NULLS LAST, p.codigo
        LIMIT 1
      ) mod ON TRUE`,
    listSelect: `c.codigo, c.nombre, c.estado, c.observacion, c.dirigidoa, c.qrys_grupo, c.cnplan,
      g.nombre AS grupo_nombre,
      COALESCE(c.modulo_codigo, mod.modulo) AS modulo_codigo,
      COALESCE(c.modulo_nombre, mod.modulo_nombre) AS modulo_nombre,
      COALESCE(c.modulo_orden, mod.modulo_orden) AS modulo_orden,
      (SELECT COUNT(*)::int FROM captemad d WHERE d.codigo = c.codigo AND COALESCE(d.estado, 'A') = 'A') AS items_count`,
    label: 'Temas de Capacitación',
    autoConsecutivo: {
      field: 'codigo',
      acnsPrefijo: 'CAPTEMA',
      pad: 6,
    },
    filterColumns: ['estado'],
  },
  temas_capacitacion_items: {
    table: 'captemad',
    pk: ['codigo', 'item'],
    columns: ['codigo', 'item', 'descripcion', 'duracion', 'estado'],
    search: ['descripcion'],
    orderBy: 'item',
    label: 'Ítems de Tema',
    filterColumns: ['codigo', 'estado'],
  },
  cronograma: {
    table: 'cronocap',
    pk: ['cnscrono'],
    columns: ['cnscrono', 'cliente', 'fecha', 'fecha_inicial', 'fecha_final', 'descripcion', 'estado', 'observacion', 'usuario'],
    search: ['cnscrono', 'descripcion', 'cliente'],
    orderBy: 'cnscrono ASC',
    label: 'Cronograma de Capacitaciones',
    autoConsecutivo: {
      field: 'cnscrono',
      acnsPrefijo: 'CRONOCAP',
      pad: 8,
    },
    filterColumns: ['cliente', 'estado'],
    listFrom: 'cronocap c LEFT JOIN clie cl ON cl.codigo = c.cliente LEFT JOIN plantrab p ON p.cnscrono = c.cnscrono',
    listSelect: 'c.cnscrono, c.cliente, c.fecha, c.fecha_inicial, c.fecha_final, c.descripcion, c.estado, c.observacion, c.usuario, cl.nombrecliente, p.cnplan, p.nombre AS plan_nombre',
    listSearch: ['c.cnscrono', 'c.descripcion', 'c.cliente', 'cl.nombrecliente'],
    listDateFilters: {
      fechaini: { column: 'c.fecha_inicial', op: 'column_gte' },
      fechafin: { column: 'c.fecha_inicial', op: 'column_lte' },
    },
    tableAlias: 'c',
  },
  cronograma_items: {
    table: 'cronocapd',
    pk: ['cnscrono', 'item'],
    columns: [
      'cnscrono', 'item', 'tema_codigo', 'tema_nombre', 'descripcion', 'duracion', 'dirigidoa',
      'fecha_probable', 'hora_sugerida', 'estado', 'fecha_real', 'observacion', 'pct_cumplimiento',
      'modulo_codigo', 'modulo_nombre', 'modulo_orden',
    ],
    search: ['tema_nombre', 'descripcion', 'dirigidoa'],
    orderBy: 'item',
    label: 'Ítems Cronograma',
    filterColumns: ['cnscrono', 'estado', 'tema_codigo'],
  },
  qrystalos_modulos: {
    table: 'qrysmod',
    pk: ['codigo'],
    columns: ['codigo', 'nombre', 'orden', 'estado'],
    search: ['codigo', 'nombre'],
    orderBy: 'orden ASC, codigo ASC',
    label: 'Módulos Qrystalos',
    filterColumns: ['estado'],
  },
  qrystalos_procesos: {
    table: 'qrysproc',
    pk: ['codigo'],
    columns: [
      'codigo', 'modulo', 'tipo', 'nombre', 'codigo_num', 'descripcion', 'duracion_sugerida', 'estado',
    ],
    search: ['codigo', 'nombre', 'codigo_num', 'descripcion'],
    orderBy: 'codigo_num ASC, codigo ASC',
    label: 'Procesos Qrystalos',
    filterColumns: ['modulo', 'estado', 'tipo'],
    listFrom: 'qrysproc p LEFT JOIN qrysmod m ON m.codigo = p.modulo',
    listSelect: 'p.*, m.nombre AS modulo_nombre',
    listSearch: ['p.codigo', 'p.nombre', 'p.codigo_num', 'p.descripcion', 'm.nombre'],
    tableAlias: 'p',
  },
  qrystalos_grupos: {
    table: 'qrysgrupo',
    pk: ['codigo'],
    columns: ['codigo', 'nombre', 'descripcion', 'estado'],
    search: ['codigo', 'nombre', 'descripcion'],
    orderBy: 'nombre ASC',
    label: 'Agrupadores Qrystalos',
    autoConsecutivo: {
      field: 'codigo',
      acnsPrefijo: 'QRYSGRUP',
      pad: 4,
      leadingPrefix: 'GRP',
    },
    filterColumns: ['estado'],
  },
  qrystalos_grupo_items: {
    table: 'qrysgrupod',
    pk: ['grupo', 'proceso'],
    columns: ['grupo', 'proceso'],
    search: ['grupo', 'proceso'],
    orderBy: 'grupo, proceso',
    label: 'Ítems de Agrupador',
    filterColumns: ['grupo'],
    listFrom: 'qrysgrupod g LEFT JOIN qrysproc p ON p.codigo = g.proceso LEFT JOIN qrysmod m ON m.codigo = p.modulo',
    listSelect: 'g.grupo, g.proceso, p.nombre AS proceso_nombre, p.modulo, m.nombre AS modulo_nombre, p.descripcion',
    listSearch: ['g.grupo', 'g.proceso', 'p.nombre', 'm.nombre'],
    tableAlias: 'g',
  },
  plan_trabajo: {
    table: 'plantrab',
    pk: ['cnplan'],
    columns: [
      'cnplan', 'cliente', 'nombre', 'fecha', 'fecha_inicial', 'fecha_final',
      'descripcion', 'estado', 'observacion', 'usuario', 'cnscrono',
    ],
    search: ['cnplan', 'nombre', 'descripcion', 'cliente'],
    orderBy: 'cnplan ASC',
    label: 'Plan de Trabajo',
    autoConsecutivo: {
      field: 'cnplan',
      acnsPrefijo: 'PLANTRAB',
      pad: 8,
    },
    filterColumns: ['cliente', 'estado'],
    listFrom: 'plantrab p LEFT JOIN clie cl ON cl.codigo = p.cliente',
    listSelect: 'p.cnplan, p.cliente, p.nombre, p.fecha, p.fecha_inicial, p.fecha_final, p.descripcion, p.estado, p.observacion, p.usuario, p.cnscrono, cl.nombrecliente',
    listSearch: ['p.cnplan', 'p.nombre', 'p.descripcion', 'p.cliente', 'cl.nombrecliente'],
    listDateFilters: {
      fechaini: { column: 'p.fecha_inicial', op: 'column_gte' },
      fechafin: { column: 'p.fecha_inicial', op: 'column_lte' },
    },
    tableAlias: 'p',
  },
  plan_trabajo_items: {
    table: 'plantrabd',
    pk: ['cnplan', 'item'],
    columns: [
      'cnplan', 'item', 'proceso_codigo', 'nombre', 'descripcion', 'orden', 'prioridad',
      'tiempo_estimado', 'estado', 'fecha_real', 'observacion', 'pct_cumplimiento',
    ],
    search: ['nombre', 'descripcion', 'proceso_codigo'],
    orderBy: 'd.orden ASC, pr.codigo_num ASC, d.item ASC',
    label: 'Actividades del Plan',
    filterColumns: ['cnplan', 'estado', 'proceso_codigo'],
    listFrom: `plantrabd d
      LEFT JOIN qrysproc pr ON pr.codigo = d.proceso_codigo
      LEFT JOIN qrysmod m ON m.codigo = pr.modulo
      LEFT JOIN LATERAL (
        SELECT g.codigo AS grupo_codigo, g.nombre AS grupo_nombre
        FROM qrysgrupod gd
        JOIN qrysgrupo g ON g.codigo = gd.grupo
        WHERE gd.proceso = d.proceso_codigo AND COALESCE(g.estado, 'A') = 'A'
        ORDER BY g.codigo
        LIMIT 1
      ) grp ON true`,
    listSelect: `d.*, pr.modulo, pr.codigo_num, pr.tipo, pr.nombre AS proc_nombre,
      m.nombre AS modulo_nombre, m.orden AS modulo_orden,
      grp.grupo_codigo, grp.grupo_nombre`,
    listSearch: ['d.nombre', 'd.descripcion', 'd.proceso_codigo'],
    tableAlias: 'd',
  },
  actividades_proyecto: {
    table: 'actproy',
    pk: ['consecutivo'],
    columns: ['consecutivo', 'fecha', 'cliente', 'ciudad', 'ingeniero', 'duracion', 'actividades', 'pendientes', 'estado'],
    search: ['consecutivo', 'cliente', 'ingeniero', 'actividades'],
    orderBy: 'fecha DESC',
    label: 'Actividades en Proyectos',
    autoConsecutivo: {
      field: 'consecutivo',
      acnsPrefijo: 'ACTP',
      leadingPrefix: 'ACTP-',
      pad: 8,
    },
    filterColumns: ['cliente', 'estado'],
    listFrom: 'actproy a LEFT JOIN clie c ON c.codigo = a.cliente',
    listSelect: 'a.*, c.nombrecliente',
    listSearch: ['a.consecutivo', 'a.cliente', 'a.ingeniero', 'a.actividades', 'c.nombrecliente'],
    tableAlias: 'a',
  },
  actas_reunion: {
    table: 'actreun',
    pk: ['consecutivo'],
    columns: ['consecutivo', 'fecha', 'cliente', 'desarrollo', 'codificacion', 'vigencia', 'version', 'estado'],
    search: ['consecutivo', 'cliente', 'desarrollo'],
    orderBy: 'fecha DESC',
    label: 'Actas de Reunión',
    autoConsecutivo: {
      field: 'consecutivo',
      acnsPrefijo: 'ACTR',
      leadingPrefix: 'ACTR-',
      pad: 8,
    },
    filterColumns: ['cliente', 'estado'],
    listFrom: 'actreun a LEFT JOIN clie c ON c.codigo = a.cliente',
    listSelect: 'a.*, c.nombrecliente',
    listSearch: ['a.consecutivo', 'a.cliente', 'a.desarrollo', 'c.nombrecliente'],
    tableAlias: 'a',
  },
  actas_reunion_compromisos: {
    table: 'actreunc',
    pk: ['consecutivo', 'item'],
    columns: ['consecutivo', 'item', 'lado', 'compromiso', 'responsable', 'fecha_inicio', 'fecha_entrega'],
    search: ['compromiso', 'responsable'],
    orderBy: 'item',
    label: 'Compromisos Acta',
    filterColumns: ['consecutivo', 'lado'],
  },
  actas_reunion_asistentes: {
    table: 'actreund',
    pk: ['consecutivo', 'item'],
    columns: ['consecutivo', 'item', 'lado', 'nombre', 'cargo', 'documento', 'firma', 'firma_fecha'],
    search: ['nombre', 'cargo'],
    orderBy: 'item',
    label: 'Asistentes Acta',
    filterColumns: ['consecutivo', 'lado'],
  },
  cambios_desarrollo: {
    table: 'devcamb',
    pk: ['consecutivo'],
    columns: [
      'consecutivo',
      'tipo',
      'rama',
      'titulo',
      'descripcion',
      'cambios',
      'estado',
      'version',
      'f_inicio',
      'f_terminacion',
      'f_integracion',
      'f_publicacion',
      'usuario',
    ],
    search: ['consecutivo', 'rama', 'titulo', 'descripcion', 'cambios', 'version'],
    orderBy: 'f_inicio DESC',
    label: 'Cambios de Desarrollo',
    filterColumns: ['estado', 'tipo'],
  },
  versiones_publicadas: {
    table: 'devver',
    pk: ['version'],
    columns: ['version', 'fecha', 'resumen', 'changelog', 'usuario'],
    search: ['version', 'resumen', 'changelog'],
    orderBy: 'fecha DESC',
    label: 'Versiones Publicadas',
  },
  vip_clientes: {
    table: 'vipclie',
    pk: ['codigo'],
    columns: [
      'codigo',
      'nombrecliente',
      'nit',
      'ciudad',
      'email',
      'notas',
      'cc_formato',
      'cc_separador',
      'cc_relleno',
      'cc_consecutivo',
      'cc_prefijo_num',
      'cuenta_banco',
      'banco_nombre',
      'cc_plantilla',
      'codigo_clie',
    ],
    search: ['codigo', 'nombrecliente', 'nit', 'ciudad'],
    orderBy: 'nombrecliente',
    label: 'Clientes VIP',
    autoConsecutivo: {
      field: 'codigo',
      acnsPrefijo: 'VIPC',
      pad: 3,
    },
  },
  vip_cuentas_cobro: {
    table: 'vipcc',
    pk: ['cns'],
    columns: [
      'codigo_cliente',
      'numero',
      'fecha_emision',
      'periodo_desde',
      'periodo_hasta',
      'valor',
      'concepto',
      'valor_letras',
      'ciudad_emision',
      'estado',
    ],
    search: ['numero', 'concepto', 'estado'],
    orderBy: 'fecha_emision DESC, cns DESC',
    label: 'Cuentas de cobro VIP',
    listFrom: 'vipcc c LEFT JOIN vipclie cl ON cl.codigo = c.codigo_cliente',
    tableAlias: 'c',
    listSelect:
      'c.cns, c.codigo_cliente, cl.nombrecliente AS cliente_nombre, c.numero, c.fecha_emision, c.periodo_desde, c.periodo_hasta, c.valor, c.estado',
    filterColumns: ['codigo_cliente'],
  },
};
