// Registro de entidades. Cada entrada describe una tabla migrada desde el
// diccionario Clarion para que el CRUD genérico sepa cómo operar sobre ella.
//
//   table     -> nombre de la tabla en PostgreSQL
//   pk        -> columna(s) que forman la clave primaria
//   columns   -> columnas que se aceptan al crear/actualizar
//   search    -> columnas usadas por el filtro de texto (?q=)
//   orderBy   -> orden por defecto del listado
//   label     -> nombre legible (Browse de Clarion del que proviene)

export const entities = {
  usuarios: {
    table: 'ususu',
    pk: ['usuario'],
    columns: ['usuario', 'nombre', 'principal'],
    search: ['usuario', 'nombre'],
    orderBy: 'usuario',
    label: 'Usuarios del Sistema',
  },
  clientes: {
    table: 'clie',
    pk: ['codigo'],
    columns: ['codigo', 'nombrecliente', 'contrato', 'ciudad', 'prefijo', 'rutaexport', 'email', 'liderproyecto', 'noticliente'],
    search: ['codigo', 'nombrecliente', 'ciudad', 'email'],
    orderBy: 'nombrecliente',
    label: 'Clientes',
    autoConsecutivo: {
      field: 'codigo',
      acnsPrefijo: 'CLIE',
      pad: 3,
    },
  },
  funcionarios: {
    table: 'clief',
    pk: ['codigo', 'documento'],
    columns: ['codigo', 'documento', 'nombre', 'cargo', 'estado', 'email', 'tratamiento'],
    search: ['documento', 'nombre', 'cargo', 'email'],
    orderBy: 'nombre',
    label: 'Funcionarios del Cliente',
    filterColumns: ['codigo', 'estado'],
    filterColumnsCaseInsensitive: ['estado'],
    excludeCapacitaParam: 'excludeCnscapacita',
  },
  soportes: {
    table: 'soport',
    pk: ['codigo'],
    columns: ['codigo', 'nombre', 'estado', 'usuario', 'clave', 'firma', 'firma_fecha'],
    listSelect: 'codigo, nombre, estado, usuario, firma_fecha',
    responseOmit: ['clave'],
    search: ['codigo', 'nombre', 'usuario'],
    orderBy: 'codigo',
    label: 'Soportes Técnicos',
    autoConsecutivo: {
      field: 'codigo',
      acnsPrefijo: 'SOP',
      pad: 4,
    },
  },
  areas_soporte: {
    table: 'soparea',
    pk: ['codigo'],
    columns: ['codigo', 'nombre', 'estado'],
    search: ['codigo', 'nombre'],
    orderBy: 'nombre',
    label: 'Áreas de Soporte',
    filterColumns: ['estado'],
    filterColumnsCaseInsensitive: ['estado'],
  },
  companias: {
    table: 'login',
    pk: ['compania'],
    columns: ['compania', 'razonsocial', 'servidor', 'bdatos', 'logo', 'nit', 'codigohab', 'direccion', 'telefono'],
    search: ['compania', 'razonsocial', 'nit'],
    orderBy: 'razonsocial',
    label: 'Compañías',
  },
  tablagenerica: {
    table: 'tgen',
    pk: ['tabla', 'campo', 'codigo'],
    columns: ['tabla', 'campo', 'codigo', 'descripcion', 'valor1', 'dato1'],
    search: ['tabla', 'campo', 'codigo', 'descripcion'],
    orderBy: 'tabla, campo, codigo',
    label: 'Tabla Genérica',
  },
  agenda: {
    table: 'agen',
    pk: ['cnsevento'],
    columns: ['cnsevento', 'descripcion', 'usuario', 'idevento', 'codigo', 'fecha', 'f_limite', 'estado'],
    search: ['cnsevento', 'descripcion', 'usuario'],
    orderBy: 'fecha DESC',
    label: 'Mi Agenda',
  },
  semanas: {
    table: 'tsema',
    pk: ['idsemana'],
    columns: ['idsemana', 'fechaini', 'fechafin', 'observacion'],
    search: ['idsemana', 'observacion'],
    orderBy: 'fechaini DESC',
    label: 'Semanas',
    listDateFilters: {
      fechaini: { column: 'fechafin', op: 'column_gte' },
      fechafin: { column: 'fechaini', op: 'column_lte' },
    },
  },
  bitacora_encabezados: {
    table: 'bite',
    pk: ['cnsbite'],
    columns: ['cnsbite', 'idsemana', 'soporte'],
    search: ['cnsbite', 'idsemana', 'soporte'],
    orderBy: 'cnsbite DESC',
    label: 'Encabezado Bitácora',
    autoConsecutivo: {
      field: 'cnsbite',
      acnsPrefijo: 'BITE',
      pad: 8,
    },
    listFrom: 'bite b INNER JOIN tsema t ON t.idsemana = b.idsemana',
    listSelect:
      'b.cnsbite, b.idsemana, b.soporte, t.observacion, t.fechaini, t.fechafin',
    listSearch: ['b.cnsbite', 'b.idsemana', 'b.soporte', 't.observacion'],
    listDateFilters: {
      fechaini: { column: 't.fechafin', op: 'column_gte' },
      fechafin: { column: 't.fechaini', op: 'column_lte' },
      ano: { column: 'b.idsemana', op: 'like_suffix' },
    },
  },
  bitacora: {
    table: 'bita',
    pk: ['cnssoporte'],
    columns: ['cnssoporte', 'fecha', 'cliente', 'soporte', 'funcionario', 'clase', 'solicitud', 'respuesta', 'estado', 'fechar', 'observaciones', 'medio', 'cnsbite', 'firma', 'firma_fecha', 'imagenes_soporte'],
    search: ['cnssoporte', 'cliente', 'funcionario', 'solicitud'],
    orderBy: 'fecha DESC',
    label: 'Bitácora de Soporte',
    autoConsecutivo: {
      field: 'cnssoporte',
      acnsPrefijo: 'BITA',
      pad: 8,
    },
    filterColumns: ['cnsbite', 'cliente', 'estado'],
    listFrom: 'bita b LEFT JOIN clie c ON c.codigo = b.cliente',
    listSelect: 'b.cnssoporte, b.fecha, b.cliente, b.soporte, b.funcionario, b.clase, b.solicitud, b.respuesta, b.estado, b.fechar, b.observaciones, b.medio, b.cnsbite, b.firma_fecha, c.nombrecliente',
    listSearch: ['b.cnssoporte', 'b.cliente', 'b.funcionario', 'b.solicitud', 'c.nombrecliente'],
    tableAlias: 'b',
  },
  informes: {
    table: 'infor',
    pk: ['consecutivo'],
    columns: ['consecutivo', 'fecha', 'cliente', 'informe', 'pendientes', 'ciudad'],
    search: ['consecutivo', 'cliente', 'informe'],
    orderBy: 'fecha DESC',
    label: 'Informes Diarios',
  },
  requerimientos: {
    table: 'desa',
    pk: ['consecutivo'],
    columns: ['consecutivo', 'cliente', 'fecha', 'requerimiento', 'desarrollo', 'modulo', 'estado', 'cnsixver', 'para', 'f_entrega', 'usuario'],
    search: ['consecutivo', 'cliente', 'requerimiento', 'modulo'],
    orderBy: 'fecha DESC',
    label: 'Requerimientos de Desarrollo',
  },
  solicitudes: {
    table: 'sreq',
    pk: ['cnssolicitud'],
    columns: ['cnssolicitud', 'usuario', 'requerimiento', 'observaciones', 'estado', 'respuesta', 'solicita', 'autoriza', 'fecha', 'f_cierre', 'modulo', 'devuelto', 'razondevol', 'idapp', 'procedimiento', 'ruta', 'usuarioasig', 'planteamiento', 'asignado'],
    search: ['cnssolicitud', 'usuario', 'requerimiento', 'solicita'],
    orderBy: 'fecha DESC',
    label: 'Solicitudes de Requerimientos',
  },
  licencias: {
    table: 'licen',
    pk: ['consecutivo'],
    columns: ['consecutivo', 'fecha', 'cliente', 'usuario', 'f_corte', 'observaciones'],
    search: ['consecutivo', 'cliente', 'usuario'],
    orderBy: 'fecha DESC',
    label: 'Licencias',
  },
  ixver: {
    table: 'ixver',
    pk: ['idreq'],
    columns: ['idreq', 'fecha', 'usuario', 'idmodulo', 'requerimiento', 'estado', 'proyecto', 'idapp', 'idproc'],
    search: ['idreq', 'usuario', 'requerimiento', 'proyecto'],
    orderBy: 'fecha DESC',
    label: 'Ixver (Requerimientos Web)',
  },
  codigospruebas: {
    table: 'codip',
    pk: ['codigo'],
    columns: ['codigo', 'descripcion', 'clase'],
    search: ['codigo', 'descripcion', 'clase'],
    orderBy: 'codigo',
    label: 'Códigos de Prueba',
  },
  asignaciones: {
    table: 'asigp',
    pk: ['consecutivo'],
    columns: ['consecutivo', 'semana', 'fecha'],
    search: ['consecutivo', 'semana'],
    orderBy: 'fecha DESC',
    label: 'Asignación de Proyectos',
  },
  entregas: {
    table: 'ent',
    pk: ['cnsentrega'],
    columns: ['cnsentrega', 'fecha', 'usuario', 'clase', 'estado', 'usuariorec', 'fecharec'],
    search: ['cnsentrega', 'usuario'],
    orderBy: 'fecha DESC',
    label: 'Entregas a Desarrollo',
  },
  variables: {
    table: 'usvgs',
    pk: ['idvariable'],
    columns: ['idvariable', 'descripcion', 'tp_variable', 'dato', 'indvigencia', 'observacion', 'tabla', 'campo_codigo'],
    search: ['idvariable', 'descripcion'],
    orderBy: 'idvariable',
    label: 'Variables del Sistema',
  },
  capacitaciones: {
    table: 'rasist',
    pk: ['cnscapacita'],
    columns: ['cnscapacita', 'fecha', 'capacitador', 'tema', 'tema1', 'tema2', 'tema3', 'duracion', 'cliente', 'compromiso', 'compromiso1', 'compromiso2', 'estado'],
    search: ['cnscapacita', 'capacitador', 'tema', 'cliente'],
    orderBy: 'fecha DESC',
    label: 'Control de Capacitaciones',
    autoConsecutivo: {
      field: 'cnscapacita',
      acnsPrefijo: 'RASIST',
      leadingPrefix: '01',
      pad: 8,
    },
  },
  asistentes: {
    table: 'rasistd',
    pk: ['cnscapacita', 'item'],
    columns: ['cnscapacita', 'item', 'documento', 'nombres', 'cargo', 'firma', 'firma_fecha'],
    search: ['documento', 'nombres', 'cargo'],
    orderBy: 'item',
    label: 'Asistentes a Capacitaciones',
    filterColumns: ['cnscapacita'],
  },
  actividades_proyecto: {
    table: 'actproy',
    pk: ['consecutivo'],
    columns: ['consecutivo', 'fecha', 'cliente', 'ciudad', 'ingeniero', 'duracion', 'actividades', 'pendientes', 'estado'],
    search: ['consecutivo', 'cliente', 'ingeniero', 'actividades'],
    orderBy: 'fecha DESC',
    label: 'Actividades en Proyectos',
    autoConsecutivo: {
      field: 'consecutivo',
      acnsPrefijo: 'ACTP',
      leadingPrefix: 'ACTP-',
      pad: 8,
    },
    filterColumns: ['cliente', 'estado'],
    listFrom: 'actproy a LEFT JOIN clie c ON c.codigo = a.cliente',
    listSelect: 'a.*, c.nombrecliente',
    listSearch: ['a.consecutivo', 'a.cliente', 'a.ingeniero', 'a.actividades', 'c.nombrecliente'],
    tableAlias: 'a',
  },
  cambios_desarrollo: {
    table: 'devcamb',
    pk: ['consecutivo'],
    columns: [
      'consecutivo',
      'tipo',
      'rama',
      'titulo',
      'descripcion',
      'cambios',
      'estado',
      'version',
      'f_inicio',
      'f_terminacion',
      'f_integracion',
      'f_publicacion',
      'usuario',
    ],
    search: ['consecutivo', 'rama', 'titulo', 'descripcion', 'cambios', 'version'],
    orderBy: 'f_inicio DESC',
    label: 'Cambios de Desarrollo',
    filterColumns: ['estado', 'tipo'],
  },
  versiones_publicadas: {
    table: 'devver',
    pk: ['version'],
    columns: ['version', 'fecha', 'resumen', 'changelog', 'usuario'],
    search: ['version', 'resumen', 'changelog'],
    orderBy: 'fecha DESC',
    label: 'Versiones Publicadas',
  },
};
