// Configuración UI de entidades del área administrativa VIP.

export const adminEntityModules = {
  vip_clientes: {
    resource: 'vip_clientes',
    title: 'Clientes VIP',
    formCols: 2,
    idField: 'codigo',
    columns: [
      { name: 'codigo', label: 'Código', field: 'codigo', align: 'left', sortable: true },
      { name: 'nombrecliente', label: 'Nombre / Razón social', field: 'nombrecliente', align: 'left', sortable: true },
      { name: 'nit', label: 'N.I.T.', field: 'nit', align: 'left' },
      { name: 'cc_formato', label: 'Formato Nro.', field: 'cc_formato', align: 'left' },
      { name: 'cc_consecutivo', label: 'Último cons.', field: 'cc_consecutivo', align: 'right' },
      { name: 'ciudad', label: 'Ciudad', field: 'ciudad', align: 'left' },
    ],
    fields: [
      { name: 'codigo', label: 'Código', type: 'text', hideOnCreate: true, fixed: true },
      { name: 'nombrecliente', label: 'Nombre / Razón social', type: 'text', required: true, colSpan: 2 },
      { name: 'nit', label: 'N.I.T.', type: 'text' },
      { name: 'ciudad', label: 'Ciudad', type: 'text' },
      {
        name: 'email',
        label: 'Email destino (Para)',
        type: 'email',
        hint: 'Correo del cliente al que se envía la cuenta de cobro. El remitente se configura en SMTP_FROM_CXC del servidor.',
      },
      {
        name: 'codigo_clie',
        label: 'Cliente operativo (soportes)',
        type: 'lookup',
        lookupResource: 'clientes',
        lookupValue: 'codigo',
        lookupLabel: 'nombrecliente',
        hint: 'Reservado para vincular soportes de bitácora (próximamente). No define destinatarios del correo.',
      },
      {
        name: 'cc_formato',
        label: 'Formato numeración cuenta de cobro',
        type: 'select',
        options: [
          { label: 'Secuencial (ej. 065, 066)', value: 'secuencial' },
          { label: 'Año-mes (ej. 2026-05 o 202605)', value: 'anio_mes' },
        ],
        default: 'anio_mes',
        colSpan: 2,
      },
      {
        name: 'cc_separador',
        label: 'Separador año-mes',
        type: 'select',
        options: [
          { label: 'Guión (2026-05)', value: '-' },
          { label: 'Sin separador (202605)', value: '' },
        ],
        default: '-',
        hint: 'Solo aplica al formato año-mes.',
      },
      {
        name: 'cc_relleno',
        label: 'Relleno secuencial (dígitos)',
        type: 'number',
        default: 3,
        hint: 'Solo aplica al formato secuencial.',
      },
      {
        name: 'cc_consecutivo',
        label: 'Último consecutivo usado',
        type: 'number',
        default: 0,
        hint: 'Indique el último número emitido (ej. 65 si la próxima será 066).',
      },
      { name: 'cc_prefijo_num', label: 'Prefijo opcional del número', type: 'text' },
      { name: 'cuenta_banco', label: 'Cuenta bancaria (opcional)', type: 'text' },
      { name: 'banco_nombre', label: 'Banco', type: 'text', default: 'Bancolombia' },
      {
        name: 'cc_plantilla',
        label: 'Plantilla cuenta de cobro (HTML)',
        type: 'vip_plantilla',
        colSpan: 2,
        hint: 'Suba un .docx desde Word o use variables {{nombre}}. El modo HTML conserva el diseño original.',
      },
      { name: 'notas', label: 'Notas', type: 'textarea', colSpan: 2 },
    ],
  },
  vip_cuentas_cobro: {
    resource: 'vip_cuentas_cobro',
    title: 'Cuentas de cobro',
    formCols: 2,
    idField: 'cns',
    pdf: true,
    email: true,
    duplicate: true,
    columns: [
      { name: 'numero', label: 'Nro.', field: 'numero', align: 'left', sortable: true },
      { name: 'cliente_nombre', label: 'Cliente', field: 'cliente_nombre', align: 'left' },
      { name: 'fecha_emision', label: 'Fecha', field: 'fecha_emision', align: 'left' },
      { name: 'periodo_desde', label: 'Desde', field: 'periodo_desde', align: 'left' },
      { name: 'periodo_hasta', label: 'Hasta', field: 'periodo_hasta', align: 'left' },
      {
        name: 'valor',
        label: 'Valor',
        field: 'valor',
        align: 'right',
        format: (v) => (v != null ? `$${Math.round(Number(v)).toLocaleString('es-CO')}` : ''),
      },
      { name: 'estado', label: 'Estado', field: 'estado', align: 'left' },
    ],
    fields: [
      {
        name: 'codigo_cliente',
        label: 'Cliente VIP',
        type: 'lookup',
        lookupResource: 'vip_clientes',
        lookupValue: 'codigo',
        lookupLabel: 'nombrecliente',
        required: true,
        hideOnEdit: true,
      },
      {
        name: 'numero',
        label: 'Número (automático)',
        type: 'text',
        hideOnCreate: true,
        fixed: true,
        hint: 'Se asigna al guardar según la configuración del cliente.',
      },
      { name: 'fecha_emision', label: 'Fecha emisión', type: 'date', default: () => new Date().toISOString().slice(0, 10) },
      { name: 'estado', label: 'Estado', type: 'select', options: ['Emitida', 'Borrador'], default: 'Emitida' },
      { name: 'periodo_desde', label: 'Periodo desde', type: 'date' },
      { name: 'periodo_hasta', label: 'Periodo hasta', type: 'date' },
      { name: 'valor', label: 'Valor ($)', type: 'number', required: true },
      {
        name: 'concepto',
        label: 'Concepto',
        type: 'textarea',
        required: true,
        colSpan: 2,
        hint: 'Ej. servicios de Asesoría, análisis de Datos y soporte técnico al área de sistemas',
      },
      { name: 'ciudad_emision', label: 'Ciudad del documento', type: 'text', colSpan: 2 },
      { name: 'valor_letras', label: 'Valor en letras', type: 'text', hideOnCreate: true, fixed: true },
    ],
  },
};

export function findAdminEntityModule(resource) {
  return adminEntityModules[resource] || null;
}
