// Configuración de módulos del sistema. Refleja el menú de la aplicación
// Clarion original (Amenu) y describe cada listado (Browse) con las columnas
// que se muestran y el formulario (Form) usado para crear/editar.
//
// Cada módulo genera:
//   - una ruta /:resource
//   - una entrada de menú en el grupo correspondiente
//   - una página de listado (GenericListPage) que usa estas columnas
//   - un formulario (GenericForm) que usa estos campos

export const ESTADO_AI_OPTIONS = [
  { label: 'Activo', value: 'A' },
  { label: 'Inactivo', value: 'I' },
];

export function fmtEstadoAI(value) {
  if (value === 'A') return 'Activo';
  if (value === 'I') return 'Inactivo';
  return value || '';
}

export const modules = [
  // -------------------- Configuración --------------------
  {
    group: 'Configuración',
    icon: 'settings',
    resource: 'clientes',
    title: 'Clientes',
    page: 'ClientesPage',
    formCols: 3,
    idField: 'codigo',
    columns: [
      { name: 'codigo', label: 'Código', field: 'codigo', align: 'left', sortable: true },
      { name: 'prefijo', label: 'Prefijo', field: 'prefijo', align: 'left' },
      { name: 'nombrecliente', label: 'Nombre', field: 'nombrecliente', align: 'left', sortable: true },
      { name: 'email', label: 'Email líder', field: 'email', align: 'left' },
      { name: 'contrato', label: 'Contrato', field: 'contrato', align: 'left' },
      { name: 'ciudad', label: 'Ciudad', field: 'ciudad', align: 'left' },
    ],
    fields: [
      { name: 'codigo', label: 'Código', type: 'text', hideOnCreate: true, fixed: true },
      { name: 'nombrecliente', label: 'Nombre del cliente', type: 'text' },
      { name: 'contrato', label: 'Tipo contrato', type: 'select', options: ['Compra', 'Arriendo', 'Mantenimiento', 'Eventual'] },
      { name: 'ciudad', label: 'Ciudad', type: 'text' },
      { name: 'prefijo', label: 'Id. alterna', type: 'text' },
      { name: 'email', label: 'Email líder del proyecto', type: 'email', hidden: true },
      {
        name: '_copiarEquipoDesde',
        label: 'Copiar equipo de trabajo desde',
        type: 'lookup',
        lookupResource: 'clientes',
        lookupValue: 'codigo',
        lookupLabel: 'nombrecliente',
        hideOnEdit: true,
        uiOnly: true,
        fillFrom: { liderproyecto: 'liderproyecto' },
        colSpan: 3,
      },
      {
        name: 'liderproyecto',
        label: 'Equipo de trabajo',
        type: 'contactosDialog',
        dialogIcon: 'groups',
        dialogHint: 'Integrantes del equipo del cliente (nombre, cargo y correo).',
        tone: 'equipo',
        syncEmail: true,
      },
      {
        name: 'noticliente',
        label: 'Contacto cliente',
        type: 'contactosDialog',
        dialogIcon: 'notifications_active',
        dialogHint: 'Destinatarios para bitácora, actas y avisos.',
        tone: 'cliente',
      },
      { name: 'rutaexport', label: 'Carpeta soporte', type: 'text', colSpan: 2, hidden: true },
    ],
    detail: {
      resource: 'funcionarios',
      fk: 'codigo',
      formCols: 4,
      idField: ['codigo', 'documento'],
      columns: [
        { name: 'documento', label: 'Documento', field: 'documento', align: 'left', sortable: true },
        { name: 'nombre', label: 'Nombre funcionario', field: 'nombre', align: 'left' },
        { name: 'tratamiento', label: 'Tratamiento', field: 'tratamiento', align: 'left' },
        { name: 'email', label: 'Email', field: 'email', align: 'left' },
        { name: 'cargo', label: 'Cargo', field: 'cargo', align: 'left' },
        { name: 'estado', label: 'Estado', field: 'estado', align: 'left' },
      ],
      fields: [
        { name: 'documento', label: 'Documento', type: 'text', required: true },
        { name: 'nombre', label: 'Nombre funcionario', type: 'text' },
        {
          name: 'tratamiento',
          label: 'Tratamiento',
          type: 'select',
          options: ['Doctor', 'Doctora', 'Sr.', 'Sra.', 'Srta.'],
          hint: 'Se usa en el saludo del correo de bitácora (ej. Doctor Juan Pérez).',
        },
        { name: 'email', label: 'Email', type: 'email' },
        { name: 'cargo', label: 'Cargo', type: 'text' },
        { name: 'estado', label: 'Estado', type: 'select', options: ['Activo', 'Inactivo'], default: 'Activo' },
      ],
    },
  },
  {
    group: 'Configuración',
    icon: 'apartment',
    resource: 'companias',
    title: 'Compañías',
    hidden: true,
    idField: 'compania',
    columns: [
      { name: 'compania', label: 'Compañía', field: 'compania', align: 'left', sortable: true },
      { name: 'razonsocial', label: 'Razón social', field: 'razonsocial', align: 'left', sortable: true },
      { name: 'nit', label: 'NIT', field: 'nit', align: 'left' },
      { name: 'telefono', label: 'Teléfono', field: 'telefono', align: 'left' },
    ],
    fields: [
      { name: 'compania', label: 'Código compañía', type: 'text', required: true },
      { name: 'razonsocial', label: 'Razón social', type: 'text' },
      { name: 'nit', label: 'NIT', type: 'text' },
      { name: 'direccion', label: 'Dirección', type: 'text' },
      { name: 'telefono', label: 'Teléfono', type: 'text' },
      { name: 'servidor', label: 'Servidor', type: 'text' },
      { name: 'bdatos', label: 'Base de datos', type: 'text' },
    ],
  },
  {
    group: 'Configuración',
    icon: 'fact_check',
    resource: 'codigospruebas',
    title: 'Códigos de Prueba',
    hidden: true,
    idField: 'codigo',
    columns: [
      { name: 'codigo', label: 'Código', field: 'codigo', align: 'left', sortable: true },
      { name: 'descripcion', label: 'Descripción', field: 'descripcion', align: 'left' },
      { name: 'clase', label: 'Clase', field: 'clase', align: 'left' },
    ],
    fields: [
      { name: 'codigo', label: 'Código', type: 'text', required: true },
      { name: 'descripcion', label: 'Descripción', type: 'textarea' },
      { name: 'clase', label: 'Clase', type: 'text' },
    ],
  },
  {
    group: 'Configuración',
    icon: 'tune',
    resource: 'variables',
    title: 'Variables del Sistema',
    hidden: true,
    idField: 'idvariable',
    columns: [
      { name: 'idvariable', label: 'Variable', field: 'idvariable', align: 'left', sortable: true },
      { name: 'descripcion', label: 'Descripción', field: 'descripcion', align: 'left' },
      { name: 'dato', label: 'Dato', field: 'dato', align: 'left' },
    ],
    fields: [
      { name: 'idvariable', label: 'Nombre de variable', type: 'text', required: true },
      { name: 'descripcion', label: 'Descripción', type: 'text' },
      { name: 'tp_variable', label: 'Tipo', type: 'text' },
      { name: 'dato', label: 'Dato', type: 'text' },
      { name: 'indvigencia', label: 'Vigencia (0/1)', type: 'number' },
      { name: 'observacion', label: 'Observación', type: 'textarea' },
    ],
  },
  {
    group: 'Configuración',
    icon: 'list_alt',
    resource: 'tablagenerica',
    title: 'Tabla Genérica',
    hidden: true,
    idField: ['tabla', 'campo', 'codigo'],
    columns: [
      { name: 'tabla', label: 'Tabla', field: 'tabla', align: 'left', sortable: true },
      { name: 'campo', label: 'Campo', field: 'campo', align: 'left' },
      { name: 'codigo', label: 'Código', field: 'codigo', align: 'left' },
      { name: 'descripcion', label: 'Descripción', field: 'descripcion', align: 'left' },
    ],
    fields: [
      { name: 'tabla', label: 'Tabla', type: 'text', required: true },
      { name: 'campo', label: 'Campo', type: 'text', required: true },
      { name: 'codigo', label: 'Código', type: 'text', required: true },
      { name: 'descripcion', label: 'Descripción', type: 'text' },
      { name: 'valor1', label: 'Valor', type: 'number' },
      { name: 'dato1', label: 'Dato', type: 'text' },
    ],
  },

  // -------------------- Desarrollo --------------------
  {
    group: 'Desarrollo',
    icon: 'new_releases',
    resource: 'control_versiones',
    title: 'Control de Versiones',
    page: 'ControlVersionesPage',
    formCols: 2,
    idField: 'consecutivo',
    columns: [
      { name: 'consecutivo', label: 'Código', field: 'consecutivo', align: 'left', sortable: true },
      { name: 'tipo', label: 'Tipo', field: 'tipo', align: 'left' },
      { name: 'titulo', label: 'Título', field: 'titulo', align: 'left', sortable: true },
      { name: 'rama', label: 'Rama Git', field: 'rama', align: 'left' },
      { name: 'estado', label: 'Estado', field: 'estado', align: 'left' },
      { name: 'f_inicio', label: 'Inicio', field: 'f_inicio', align: 'left', format: (v) => fmtDate(v) },
      { name: 'f_terminacion', label: 'Fin', field: 'f_terminacion', align: 'left', format: (v) => fmtDate(v) },
      { name: 'version', label: 'Versión', field: 'version', align: 'left' },
    ],
    fields: [
      { name: 'consecutivo', label: 'Código', type: 'text', hideOnCreate: true, fixed: true },
      {
        name: 'tipo',
        label: 'Tipo de rama',
        type: 'select',
        options: [
          { label: 'Feature → feature/devdesNNN', value: 'feature' },
          { label: 'Fix → fix/devfixNNN', value: 'fix' },
          { label: 'Hotfix → hotfix/devhotNNN', value: 'hotfix' },
        ],
        required: true,
        default: 'feature',
      },
      { name: 'rama', label: 'Rama Git (automática)', type: 'text', hideOnCreate: true, fixed: true, colSpan: 2 },
      { name: 'titulo', label: 'Título', type: 'text', required: true, colSpan: 2 },
      { name: 'descripcion', label: 'Descripción / requerimiento', type: 'textarea', colSpan: 2 },
      { name: 'cambios', label: 'Cambios realizados', type: 'textarea', colSpan: 2, hideOnCreate: true },
      {
        name: 'estado',
        label: 'Estado',
        type: 'select',
        options: [
          { label: 'En desarrollo', value: 'en_desarrollo' },
          { label: 'Integrado', value: 'integrado' },
          { label: 'Publicado', value: 'publicado' },
        ],
        default: 'en_desarrollo',
        hideOnCreate: true,
      },
      { name: 'version', label: 'Versión publicada', type: 'text', hideOnCreate: true, fixed: true },
    ],
  },
  {
    group: 'Desarrollo',
    resource: 'cambios_desarrollo',
    title: 'Cambios (CRUD)',
    hidden: true,
    idField: 'consecutivo',
    columns: [],
    fields: [],
  },
  {
    group: 'Desarrollo',
    resource: 'versiones_publicadas',
    title: 'Versiones (CRUD)',
    hidden: true,
    idField: 'version',
    columns: [],
    fields: [],
  },
  {
    group: 'Desarrollo',
    icon: 'developer_board',
    resource: 'ixver',
    title: 'Ixver',
    hidden: true,
    idField: 'idreq',
    columns: [
      { name: 'idreq', label: 'ID Req', field: 'idreq', align: 'left', sortable: true },
      { name: 'fecha', label: 'Fecha', field: 'fecha', align: 'left', format: (v) => fmtDate(v) },
      { name: 'usuario', label: 'Usuario', field: 'usuario', align: 'left' },
      { name: 'proyecto', label: 'Proyecto', field: 'proyecto', align: 'left' },
      { name: 'estado', label: 'Estado', field: 'estado', align: 'left' },
    ],
    fields: [
      { name: 'idreq', label: 'ID Requerimiento', type: 'text', required: true },
      { name: 'fecha', label: 'Fecha', type: 'date' },
      { name: 'usuario', label: 'Usuario', type: 'text' },
      { name: 'idmodulo', label: 'Módulo', type: 'text' },
      { name: 'requerimiento', label: 'Requerimiento', type: 'textarea' },
      { name: 'proyecto', label: 'Proyecto', type: 'text' },
      { name: 'estado', label: 'Estado', type: 'text' },
    ],
  },
  {
    group: 'Desarrollo',
    icon: 'assignment',
    resource: 'requerimientos',
    title: 'Requerimientos',
    hidden: true,
    idField: 'consecutivo',
    columns: [
      { name: 'consecutivo', label: 'Consecutivo', field: 'consecutivo', align: 'left', sortable: true },
      { name: 'cliente', label: 'Cliente', field: 'cliente', align: 'left' },
      { name: 'fecha', label: 'Fecha', field: 'fecha', align: 'left', format: (v) => fmtDate(v) },
      { name: 'modulo', label: 'Módulo', field: 'modulo', align: 'left' },
      { name: 'estado', label: 'Estado', field: 'estado', align: 'left' },
    ],
    fields: [
      { name: 'consecutivo', label: 'Consecutivo', type: 'text', required: true },
      { name: 'cliente', label: 'Cliente', type: 'text' },
      { name: 'fecha', label: 'Fecha', type: 'date' },
      { name: 'requerimiento', label: 'Requerimiento', type: 'textarea' },
      { name: 'desarrollo', label: 'Desarrollo', type: 'textarea' },
      { name: 'modulo', label: 'Módulo', type: 'text' },
      { name: 'estado', label: 'Estado', type: 'text' },
      { name: 'para', label: 'Para', type: 'text' },
      { name: 'f_entrega', label: 'Fecha entrega', type: 'date' },
      { name: 'usuario', label: 'Usuario', type: 'text' },
    ],
  },
  {
    group: 'Desarrollo',
    icon: 'send',
    resource: 'entregas',
    title: 'Entregas',
    hidden: true,
    idField: 'cnsentrega',
    columns: [
      { name: 'cnsentrega', label: 'Consecutivo', field: 'cnsentrega', align: 'left', sortable: true },
      { name: 'fecha', label: 'Fecha', field: 'fecha', align: 'left', format: (v) => fmtDate(v) },
      { name: 'usuario', label: 'Usuario', field: 'usuario', align: 'left' },
      { name: 'estado', label: 'Estado', field: 'estado', align: 'left' },
    ],
    fields: [
      { name: 'cnsentrega', label: 'Consecutivo', type: 'text', required: true },
      { name: 'fecha', label: 'Fecha', type: 'date' },
      { name: 'usuario', label: 'Usuario', type: 'text' },
      { name: 'clase', label: 'Clase', type: 'text' },
      { name: 'estado', label: 'Estado', type: 'text' },
    ],
  },

  // -------------------- Soporte --------------------
  {
    group: 'Soporte',
    icon: 'mark_email_unread',
    resource: 'correos',
    title: 'Bandeja de Correos',
    page: 'BandejaCorreosPage',
    columns: [],
    fields: [],
  },
  {
    group: 'Soporte',
    icon: 'assignment_turned_in',
    resource: 'actividades_proyecto',
    title: 'Informe de Actividades',
    page: 'ActividadesProyectoPage',
    formCols: 2,
    idField: 'consecutivo',
    columns: [
      { name: 'consecutivo', label: 'Consecutivo', field: 'consecutivo', align: 'left', sortable: true },
      { name: 'fecha', label: 'Fecha', field: 'fecha', align: 'left', format: (v) => fmtDate(v) },
      { name: 'nombrecliente', label: 'Proyecto / Cliente', field: 'nombrecliente', align: 'left' },
      { name: 'ingeniero', label: 'Ingeniero', field: 'ingeniero', align: 'left' },
      { name: 'estado', label: 'Estado', field: 'estado', align: 'left' },
    ],
    fields: [
      { name: 'consecutivo', label: 'Consecutivo', type: 'text', hideOnCreate: true, fixed: true },
      { name: 'estado', label: 'Estado', type: 'text', fixed: true, hideOnCreate: true },
      { name: 'fecha', label: 'Fecha de soporte', type: 'date', defaultToday: true, required: true },
      {
        name: 'cliente',
        label: 'Proyecto / Cliente',
        type: 'lookup',
        lookupResource: 'clientes',
        lookupValue: 'codigo',
        lookupLabel: 'nombrecliente',
        fillFrom: { ciudad: 'ciudad' },
        required: true,
      },
      { name: 'ciudad', label: 'Ciudad', type: 'text' },
      {
        name: 'ingeniero',
        label: 'Ingeniero asignado de soporte',
        type: 'lookup',
        lookupResource: 'soportes',
        lookupValue: 'nombre',
        lookupLabel: 'nombre',
        lookupCodeField: 'codigo',
      },
      { name: 'duracion', label: 'Duración', type: 'text' },
      { name: 'actividades', label: 'Actividades realizadas', type: 'textarea', colSpan: 2 },
      { name: 'pendientes', label: 'Actividades pendientes', type: 'textarea', colSpan: 2 },
    ],
  },
  {
    group: 'Soporte',
    icon: 'support_agent',
    resource: 'bitacora',
    title: 'Bitácora',
    page: 'BitacoraPage',
    notifyEmail: true,
    formCols: 3,
    idField: 'cnssoporte',
    columns: [
      { name: 'cnssoporte', label: 'Nro. Soporte', field: 'cnssoporte', align: 'left', sortable: true },
      { name: 'fecha', label: 'Fecha', field: 'fecha', align: 'left', format: (v) => fmtDate(v) },
      { name: 'cliente', label: 'Cliente', field: 'cliente', align: 'left' },
      { name: 'nombrecliente', label: 'Nombre cliente', field: 'nombrecliente', align: 'left' },
      { name: 'clase', label: 'Tipo', field: 'clase', align: 'left' },
      { name: 'estado', label: 'Estado', field: 'estado', align: 'left' },
    ],
    fields: [
      { name: 'cnssoporte', label: 'Consecutivo', type: 'text', hideOnCreate: true },
      { name: 'cnsbite', label: 'Semana', type: 'text', hideOnCreate: true, fixed: true },
      { name: 'estado', label: 'Estado', type: 'text', fixed: true, hideOnCreate: true },
      {
        name: 'cliente',
        label: 'Cliente',
        type: 'lookup',
        lookupResource: 'clientes',
        lookupValue: 'codigo',
        lookupLabel: 'nombrecliente',
        required: true,
      },
      {
        name: 'fecha',
        label: 'Fecha soporte',
        type: 'date',
        required: true,
        dateContextKeys: { min: 'semanaFechaini', max: 'semanaFechafin' },
      },
      {
        name: 'funcionario',
        label: 'Funcionario',
        type: 'lookup',
        lookupResource: 'funcionarios',
        lookupValue: 'nombre',
        lookupLabel: 'nombre',
        lookupCodeField: 'documento',
        lookupExtraParams: { estado: 'Activo' },
        lookupContextKeys: { codigo: 'cliente' },
        lookupRequires: 'cliente',
      },
      {
        name: 'soporte',
        label: 'Área soporte',
        type: 'lookup',
        lookupResource: 'areas_soporte',
        lookupValue: 'codigo',
        lookupLabel: 'nombre',
        lookupExtraParams: { estado: 'A' },
      },
      {
        name: 'clase',
        label: 'Clase soporte',
        type: 'select',
        default: 'Soporte',
        options: ['Soporte', 'Informacion', 'Reportes', 'Parametrización', 'Correccion', 'Capacitacion'],
      },
      {
        name: 'medio',
        label: 'Medio',
        type: 'select',
        default: 'Remoto',
        options: ['Presencial', 'Remoto'],
      },
      { name: 'solicitud', label: 'Solicitud', type: 'textarea', colSpan: 3 },
      { name: 'observaciones', label: 'Observaciones', type: 'textarea', colSpan: 3 },
      {
        name: 'imagenes_soporte',
        label: 'Imágenes de soporte',
        type: 'images',
        colSpan: 3,
        hint: 'Capturas o fotos del trabajo realizado. Se incluyen en el correo de bitácora.',
      },
    ],
  },
  {
    group: 'Soporte',
    resource: 'bitacora_encabezados',
    title: 'Semana bitácora',
    hidden: true,
    formCols: 2,
    idField: 'cnsbite',
    columns: [
      { name: 'cnsbite', label: 'Consecutivo', field: 'cnsbite', align: 'left', sortable: true },
      { name: 'idsemana', label: 'Semana', field: 'idsemana', align: 'left' },
      { name: 'observacion', label: 'Datos', field: 'observacion', align: 'left' },
      { name: 'soporte', label: 'Realizado por', field: 'soporte', align: 'left' },
      { name: 'fechaini', label: 'Desde', field: 'fechaini', align: 'left', format: (v) => fmtDate(v) },
      { name: 'fechafin', label: 'Hasta', field: 'fechafin', align: 'left', format: (v) => fmtDate(v) },
    ],
    fields: [
      { name: 'cnsbite', label: 'Consecutivo', type: 'text', hideOnCreate: true, fixed: true },
      {
        name: 'idsemana',
        label: 'Semana',
        type: 'lookup',
        lookupResource: 'semanas',
        lookupValue: 'idsemana',
        lookupLabel: 'observacion',
        lookupContextKeys: { fechaini: 'fechaini', fechafin: 'fechafin' },
        required: true,
      },
      { name: 'soporte', label: 'Realizado por', type: 'text', colSpan: 2 },
    ],
  },
  {
    group: 'Soporte',
    resource: 'semanas',
    title: 'Semanas',
    hidden: true,
    idField: 'idsemana',
    columns: [
      { name: 'idsemana', label: 'Semana', field: 'idsemana', align: 'left', sortable: true },
      { name: 'observacion', label: 'Descripción', field: 'observacion', align: 'left' },
      { name: 'fechaini', label: 'Inicio', field: 'fechaini', align: 'left', format: (v) => fmtDate(v) },
      { name: 'fechafin', label: 'Fin', field: 'fechafin', align: 'left', format: (v) => fmtDate(v) },
    ],
    fields: [
      { name: 'idsemana', label: 'Semana', type: 'text', required: true },
      { name: 'fechaini', label: 'Fecha inicio', type: 'date' },
      { name: 'fechafin', label: 'Fecha fin', type: 'date' },
      { name: 'observacion', label: 'Observación', type: 'text', colSpan: 2 },
    ],
  },
  {
    group: 'Soporte',
    icon: 'event',
    resource: 'agenda',
    title: 'Mi Agenda',
    hidden: true,
    idField: 'cnsevento',
    columns: [
      { name: 'cnsevento', label: 'Consecutivo', field: 'cnsevento', align: 'left', sortable: true },
      { name: 'descripcion', label: 'Descripción', field: 'descripcion', align: 'left' },
      { name: 'usuario', label: 'Usuario', field: 'usuario', align: 'left' },
      { name: 'fecha', label: 'Fecha', field: 'fecha', align: 'left', format: (v) => fmtDate(v) },
      { name: 'estado', label: 'Estado', field: 'estado', align: 'left' },
    ],
    fields: [
      { name: 'cnsevento', label: 'Consecutivo', type: 'text', required: true },
      { name: 'descripcion', label: 'Descripción', type: 'text' },
      { name: 'usuario', label: 'Usuario', type: 'text' },
      { name: 'idevento', label: 'Id evento', type: 'text' },
      { name: 'codigo', label: 'Código', type: 'text' },
      { name: 'fecha', label: 'Fecha', type: 'date' },
      { name: 'f_limite', label: 'Fecha límite', type: 'date' },
      { name: 'estado', label: 'Estado', type: 'text' },
    ],
  },
  {
    group: 'Soporte',
    icon: 'description',
    resource: 'informes',
    title: 'Informes Diarios',
    hidden: true,
    idField: 'consecutivo',
    columns: [
      { name: 'consecutivo', label: 'Consecutivo', field: 'consecutivo', align: 'left', sortable: true },
      { name: 'fecha', label: 'Fecha', field: 'fecha', align: 'left', format: (v) => fmtDate(v) },
      { name: 'cliente', label: 'Cliente', field: 'cliente', align: 'left' },
      { name: 'ciudad', label: 'Ciudad', field: 'ciudad', align: 'left' },
    ],
    fields: [
      { name: 'consecutivo', label: 'Consecutivo', type: 'text', required: true },
      { name: 'fecha', label: 'Fecha', type: 'date' },
      { name: 'cliente', label: 'Cliente', type: 'text' },
      { name: 'ciudad', label: 'Ciudad', type: 'text' },
      { name: 'informe', label: 'Informe', type: 'textarea' },
      { name: 'pendientes', label: 'Pendientes', type: 'textarea' },
    ],
  },
  {
    group: 'Soporte',
    icon: 'assignment_ind',
    resource: 'asignaciones',
    title: 'Asignación de Proyectos',
    hidden: true,
    idField: 'consecutivo',
    columns: [
      { name: 'consecutivo', label: 'Consecutivo', field: 'consecutivo', align: 'left', sortable: true },
      { name: 'semana', label: 'Semana', field: 'semana', align: 'left' },
      { name: 'fecha', label: 'Fecha', field: 'fecha', align: 'left', format: (v) => fmtDate(v) },
    ],
    fields: [
      { name: 'consecutivo', label: 'Consecutivo', type: 'text', required: true },
      { name: 'semana', label: 'Semana', type: 'text' },
      { name: 'fecha', label: 'Fecha', type: 'date' },
    ],
  },
  {
    group: 'Soporte',
    icon: 'school',
    resource: 'capacitaciones',
    title: 'Control Capacitaciones',
    page: 'CapacitacionesPage',
    notifyEmail: true,
    formCols: 3,
    idField: 'cnscapacita',
    columns: [
      { name: 'cnscapacita', label: 'Consecutivo', field: 'cnscapacita', align: 'left', sortable: true },
      { name: 'fecha', label: 'Fecha', field: 'fecha', align: 'left', format: (v) => fmtDate(v) },
      { name: 'capacitador', label: 'Capacitador', field: 'capacitador', align: 'left' },
      { name: 'cliente', label: 'Cliente', field: 'cliente', align: 'left' },
      { name: 'duracion', label: 'Duración (min)', field: 'duracion', align: 'right' },
      { name: 'tema', label: 'Tema', field: 'tema', align: 'left' },
      { name: 'estado', label: 'Estado', field: 'estado', align: 'left' },
    ],
    fields: [
      { name: 'cnscapacita', label: 'Consecutivo', type: 'text', hideOnCreate: true },
      { name: 'estado', label: 'Estado', type: 'text', fixed: true, hideOnCreate: true },
      { name: 'fecha', label: 'Fecha', type: 'date', defaultToday: true },
      {
        name: 'cliente',
        label: 'Cliente',
        type: 'lookup',
        lookupResource: 'clientes',
        lookupValue: 'codigo',
        lookupLabel: 'nombrecliente',
        required: true,
      },
      { name: 'capacitador', label: 'Capacitador', type: 'text' },
      { name: 'tema', label: 'Tema', type: 'text' },
      { name: 'tema1', label: 'Tema 2', type: 'text' },
      { name: 'tema2', label: 'Tema 3', type: 'text' },
      { name: 'tema3', label: 'Tema 4', type: 'text' },
      { name: 'duracion', label: 'Duración (minutos)', type: 'number' },
      { name: 'compromiso', label: 'Compromiso', type: 'textarea' },
      { name: 'compromiso1', label: 'Compromiso 2', type: 'textarea' },
      { name: 'compromiso2', label: 'Compromiso 3', type: 'textarea' },
    ],
    detail: {
      resource: 'asistentes',
      fk: 'cnscapacita',
      formCols: 4,
      idField: ['cnscapacita', 'item'],
      columns: [
        { name: 'item', label: 'Item', field: 'item', align: 'right', sortable: true },
        { name: 'documento', label: 'Documento', field: 'documento', align: 'left' },
        { name: 'nombres', label: 'Nombres', field: 'nombres', align: 'left' },
        { name: 'cargo', label: 'Cargo', field: 'cargo', align: 'left' },
      ],
      fields: [
        { name: 'item', label: 'Item', type: 'number', hideOnCreate: true },
        {
          name: 'documento',
          label: 'Funcionario',
          type: 'lookup',
          lookupResource: 'funcionarios',
          lookupValue: 'documento',
          lookupLabel: 'nombre',
          lookupExtraParams: { estado: 'Activo' },
          lookupContextKeys: { codigo: 'cliente', excludeCnscapacita: 'cnscapacita' },
          fillFrom: { nombres: 'nombre', cargo: 'cargo' },
          required: true,
        },
        { name: 'nombres', label: 'Nombres', type: 'text', fixed: true },
        { name: 'cargo', label: 'Cargo', type: 'text', fixed: true },
      ],
    },
  },
  {
    group: 'Soporte',
    icon: 'vpn_key',
    resource: 'licencias',
    title: 'Licencias',
    hidden: true,
    idField: 'consecutivo',
    columns: [
      { name: 'consecutivo', label: 'Consecutivo', field: 'consecutivo', align: 'left', sortable: true },
      { name: 'cliente', label: 'Cliente', field: 'cliente', align: 'left' },
      { name: 'fecha', label: 'Fecha', field: 'fecha', align: 'left', format: (v) => fmtDate(v) },
      { name: 'f_corte', label: 'Corte', field: 'f_corte', align: 'left', format: (v) => fmtDate(v) },
    ],
    fields: [
      { name: 'consecutivo', label: 'Consecutivo', type: 'text', required: true },
      { name: 'fecha', label: 'Fecha', type: 'date' },
      { name: 'cliente', label: 'Cliente', type: 'text' },
      { name: 'usuario', label: 'Usuario', type: 'text' },
      { name: 'f_corte', label: 'Fecha de corte', type: 'date' },
      { name: 'observaciones', label: 'Observaciones', type: 'textarea' },
    ],
  },
  {
    group: 'Soporte',
    icon: 'category',
    resource: 'areas_soporte',
    title: 'Áreas de Soporte',
    idField: 'codigo',
    columns: [
      { name: 'codigo', label: 'Código', field: 'codigo', align: 'left', sortable: true },
      { name: 'nombre', label: 'Nombre', field: 'nombre', align: 'left', sortable: true },
      { name: 'estado', label: 'Estado', field: 'estado', align: 'left', format: fmtEstadoAI },
    ],
    fields: [
      { name: 'codigo', label: 'Código', type: 'text', required: true },
      { name: 'nombre', label: 'Nombre', type: 'text', required: true },
      {
        name: 'estado',
        label: 'Estado',
        type: 'select',
        options: ESTADO_AI_OPTIONS,
        default: 'A',
      },
    ],
  },
  {
    group: 'Soporte',
    icon: 'engineering',
    resource: 'soportes',
    title: 'Técnicos de Soporte',
    idField: 'codigo',
    formCols: 4,
    fetchOnEdit: true,
    columns: [
      { name: 'codigo', label: 'Código', field: 'codigo', align: 'left', sortable: true },
      { name: 'nombre', label: 'Nombre', field: 'nombre', align: 'left' },
      { name: 'usuario', label: 'Usuario acceso', field: 'usuario', align: 'left' },
      { name: 'estado', label: 'Estado', field: 'estado', align: 'left', format: fmtEstadoAI },
      {
        name: 'firma_fecha',
        label: 'Firma',
        field: 'firma_fecha',
        align: 'center',
        format: (v) => (v ? 'Registrada' : 'Pendiente'),
      },
    ],
    fields: [
      { name: 'codigo', label: 'Código', type: 'text', hideOnCreate: true, fixed: true },
      { name: 'nombre', label: 'Nombre', type: 'text', required: true },
      {
        name: 'usuario',
        label: 'Usuario de acceso',
        type: 'text',
        hint: 'Para iniciar sesión en DevSoporte',
      },
      {
        name: 'clave',
        label: 'Contraseña',
        type: 'password',
        editHint: 'Dejar vacío para no cambiar',
        hint: 'Requerida junto con el usuario de acceso',
      },
      {
        name: 'estado',
        label: 'Estado',
        type: 'select',
        options: ESTADO_AI_OPTIONS,
        default: 'A',
      },
      { name: 'firma', label: 'Firma digital', type: 'signature' },
    ],
  },

  // -------------------- Solicitudes --------------------
  {
    group: 'Solicitudes',
    icon: 'inbox',
    resource: 'solicitudes',
    title: 'Solicitudes de Requerimientos',
    hidden: true,
    idField: 'cnssolicitud',
    columns: [
      { name: 'cnssolicitud', label: 'Consecutivo', field: 'cnssolicitud', align: 'left', sortable: true },
      { name: 'usuario', label: 'Usuario', field: 'usuario', align: 'left' },
      { name: 'solicita', label: 'Solicita', field: 'solicita', align: 'left' },
      { name: 'estado', label: 'Estado', field: 'estado', align: 'left' },
    ],
    fields: [
      { name: 'cnssolicitud', label: 'Consecutivo', type: 'text', required: true },
      { name: 'usuario', label: 'Usuario', type: 'text' },
      { name: 'solicita', label: 'Solicita', type: 'text' },
      { name: 'requerimiento', label: 'Requerimiento', type: 'textarea' },
      { name: 'observaciones', label: 'Observaciones', type: 'textarea' },
      { name: 'planteamiento', label: 'Planteamiento', type: 'textarea' },
      { name: 'estado', label: 'Estado', type: 'text' },
      { name: 'modulo', label: 'Módulo', type: 'text' },
    ],
  },

  // -------------------- Seguridad --------------------
  {
    group: 'Seguridad',
    icon: 'people',
    resource: 'usuarios',
    title: 'Usuarios',
    hidden: true,
    idField: 'usuario',
    columns: [
      { name: 'usuario', label: 'Usuario', field: 'usuario', align: 'left', sortable: true },
      { name: 'nombre', label: 'Nombre', field: 'nombre', align: 'left' },
      { name: 'principal', label: 'Principal', field: 'principal', align: 'center' },
    ],
    fields: [
      { name: 'usuario', label: 'Usuario', type: 'text', required: true },
      { name: 'nombre', label: 'Nombre', type: 'text' },
      { name: 'principal', label: 'Principal (0/1)', type: 'number' },
    ],
  },
];

function fmtDate(v) {
  if (!v) return '';
  const d = new Date(v);
  if (Number.isNaN(d.getTime())) return v;
  return d.toLocaleDateString();
}

// Módulos visibles en menú e inicio. Los ocultos siguen accesibles por URL directa si se necesitan.
export function visibleModules() {
  return modules.filter((m) => !m.hidden);
}

// Agrupa los módulos visibles por su propiedad "group" para construir el menú.
export function modulesByGroup() {
  const groups = {};
  for (const m of visibleModules()) {
    (groups[m.group] = groups[m.group] || []).push(m);
  }
  return groups;
}

export function findModule(resource) {
  return modules.find((m) => m.resource === resource);
}
